package com.wire.dao.model

import org.jetbrains.exposed.sql.Table
import org.jetbrains.exposed.sql.javatime.timestamp

/**
 * Table that stores created and updated.
 */
open class ChangesAwareTable(name: String) : Table(name) {
    /**
     * When this record was created.
     */
    val created = timestamp("created")

    /**
     * When this record was updated. By default, same value as [created].
     */
    val updated = timestamp("updated")

    /**
     * When was this record deleted. If null, the record is active.
     */
    val deleted = timestamp("deleted").nullable()
}

/**
 * Table that has as a primary key autogenerated UUID.
 */
open class UUIDTable(name: String) : Table(name) {

    /**
     * Primary key of each entity.
     */
    val id = uuid("id").autoGenerate()

    override val primaryKey = PrimaryKey(id)
}

open class ManagedTable(name: String) : ChangesAwareTable(name) {
    /**
     * Primary key of each entity.
     */
    val id = uuid("id").autoGenerate()

    /**
     * Domain to which does this entity belong to.
     */
    val domain = text("domain")

    override val primaryKey = PrimaryKey(id)
}
