name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  native_tests:
    uses: ./.github/workflows/native-tests.yml
    secrets:
      webhook: ${{ secrets.WEBHOOK_CI }}

  docker_build_test:
    uses: ./.github/workflows/docker.yml
    secrets:
      registry: docker.io
      image: ci_test
      publish: false
