name: Native Tests

on:
  workflow_call:
    secrets:
      webhook:
        required: true

jobs:
  native_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container: eclipse-temurin:17-jdk
    # enable postgres
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
    # and run the pipeline
    steps:
      - uses: actions/checkout@v3

      - name: Update base image & Install git
        run: |
          apt update
          apt upgrade -y
          apt install git -y
          git init

      - name: Setup java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # override template environment variables
      - name: Setup Environment Variables
        run: |
          echo "DATABASE_URL=jdbc:postgresql://postgres:5432/postgres"  >> $GITHUB_ENV
          echo "DATABASE_USERNAME=postgres" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=postgres" >> $GITHUB_ENV

      - name: Execute Unit tests
        run: |
          ./gradlew test --info

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Gradle Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: false

      # Send webhook to Wire using Slack Bot
      - name: Webhook to Wire
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Native CI pipeline
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.webhook }}
        # Send message only if previous step failed
        if: failure()
